     name: Update snake

     on:
       schedule:
         - cron: '0 0 * * *'
       workflow_dispatch:

     jobs:
       update-snake:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout
             uses: actions/checkout@v2
           - name: Generate snake
             uses: Platane/snk@master
             with:
               github_user: 'ivan-kulik'
               svg_out: 'output/github-contribution-grid-snake.svg'
           - name: Commit and push if changed
             run: |
               git config --local user.email "<>"
               git config --local user.name "<>"
               git add output/github-contribution-grid-snake.svg
               git commit -m "Update snake" || echo "No changes to commit"
               git push
     
